# version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=fws_user
      - POSTGRES_PASSWORD=fsw_password
      - POSTGRES_DB=fws_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: